### ISSUE TITLE
Script error when clicking place order button - Stopping Orders

### ISSUE THREAD

**Issue by rjmccollam** [hps/heartland-woocommerce-plugin#146]
A client that uses this plugin reported that people were unable to checkout. After looking into it I noticed that when the Place Order button is clicked there is a script error in the console that does not let the order be processed.

Here is a screenshot:
<img width="2546" alt="dreamshot" src="https://user-images.githubusercontent.com/1494002/34116433-4149059c-e3de-11e7-8bf3-61fab78573b2.png">

I have updated WordPress, WooCommerce, and this plugin to the latest versions as of this post and the issue still remains. The client was accepting payments fine up until recently. 

For reference the site is https://othellos.us/giftcards/

**Comment by slogsdon** [comment]
@rjmccollam It looks like the public API key in use is incorrect which is causing our tokenization service to respond with a 403 error:

![screen shot 2017-12-18 at 11 33 39 am](https://user-images.githubusercontent.com/647624/34116717-60b70b32-e3e7-11e7-8ea9-41fa0a958828.png)

Are you able to ensure that the public API key in use is correct for the account? If you need assistance with this process, please reach out to our Product Integration Support team: SecureSubmitCert@e-hps.com.

**Comment by rjmccollam** [comment]
I will confirm with the client that the keys we have our accurate and if they are reach out to that email address for further help. Thank you for your quick response.

**Comment by slogsdon** [comment]
@rjmccollam Sounds like a plan. I'm closing this issue for now, but if it ends up being an issue with the plugin, we'll open this again for tracking. Feel free to open it if you feel the need as well.

**Comment by rjmccollam** [comment]
We confirmed the keys and are still experiencing the same issue. Would it be best to use the email above for support, or continue this thread?

**Comment by slogsdon** [comment]
@rjmccollam Please reach out to our Product Integration Support team: SecureSubmitCert@e-hps.com. They will loop in my team if they find it necessary. Thanks!
