### ISSUE TITLE
SecureSubmit error: Please enter your secret key here

### ISSUE THREAD

**Issue by don-paramountny** [hps/heartland-woocommerce-plugin#165]
I just installed the plugin and I'm getting the following error:
SecureSubmit error: Please enter your secret key here

When I click on the here link, it takes me to a blank page that says:
Cannot load woocommerce.

The URL for that blank page is:
wp-admin/admin.php?page=woocommerce&tab=payment_gateways&subtab=gateway-securesubmit

How do I resolve this error so that I can specify the secret key?

Thank you!

**Comment by slogsdon** [comment]
Hi @don-paramountny! Apologies for the inconvenience here. I will work with the team to see what may have caused this.

In the meantime, you should be able to configure the necessary settings via the WooCommerce > Settings > Payments page:

<img width="1510" alt="Screen Shot 2019-10-24 at 12 36 51 PM" src="https://user-images.githubusercontent.com/647624/67506473-179af980-f65b-11e9-80f6-c2f14630b24f.png">

Be sure to click the Set up / Manage button associated with the Secure Submit payment method option.

Let us know if you run into any issues with this.

**Comment by don-paramountny** [comment]
I was able to locate the area in the settings where I can specify the API keys, so I may have added that error in haste. We’re currently in the process of setting up a developer account with Heartland, so currently we don’t have anything to enter in those fields. I’ll let you know if we run into any issues at that point. Thank you so much for getting back to me!

Don Israel
Marketing Manager
The Paramount
370 New York Avenue
Huntington, NY 11743
P: (631) 673-7300
C: (516) 607-7931
don@paramountny.com<mailto:don@paramountny.com>
www.paramountny.com<http://www.paramountny.com/>
[signature_193826558]

**Comment by JeffreySummers** [comment]
I'm getting the exact same issue and the plugin won't activate due to the fatal error:
Fatal error: Cannot declare class WooCommerceSecureSubmitGateway, because the name is already in use in /home/opfmdg89n0je/public_html/wp-content/plugins/heartland-woocommerce-plugin-master/gateway-securesubmit.php on line 12
