### ISSUE TITLE
Error messages are not displayed in some cases

### ISSUE THREAD

**Issue by vkobrenko** [hps/heartland-woocommerce-plugin#194]
After updating the plugin from version `1.13.1` to `2.1.1`, I found an issue where some error messages were not displayed as expected. Namely, in the following cases:

### Case A. User entered invalid card details.
**Actual behavior**: a user doesn't receive any error message after clicking on the "Place Order" button.
**Expected**: a user gets the following message: "Card number is invalid."

| Actual (v2.1.1)  | Expected (as in version 1.13.1 ) |
| ------------- | ------------- |
| <img width="1439" alt="image" src="https://user-images.githubusercontent.com/93373540/205290654-eb148e1f-da2e-4a66-bd15-450ea7cedb14.png">  | <img width="1439" alt="image" src="https://user-images.githubusercontent.com/93373540/205291565-b8cae9ca-a95d-4b84-89fd-ca2bbcc750cb.png">  |

### Case B. The credit card form was not filled out at all.
**Actual behavior**: a user doesn't receive any error message after clicking on the "Place Order" button.
**Expected**: a user gets the following message: "Card number is missing."

| Actual (v2.1.1)  | Expected (as in version 1.13.1 ) |
| ------------- | ------------- |
| <img width="1439" alt="image" src="https://user-images.githubusercontent.com/93373540/205290830-d5e5ac28-26fc-46dd-a74b-8b748d2f3666.png">  | <img width="1439" alt="image" src="https://user-images.githubusercontent.com/93373540/205291359-8bffe758-844c-42f1-af09-f40b5b56a279.png">   |

**Comment by vkobrenko** [comment]
Implemented a change that fixes this issue - https://github.com/hps/heartland-woocommerce-plugin/pull/195

**Comment by MSmedal** [comment]
Will be addressed in v2.2.1 release
