### ISSUE TITLE
Cart with Subscriptions Incorrectly Allowing Gift Cards for Payment

### ISSUE THREAD

**Issue by tflight** [hps/heartland-woocommerce-plugin#198]
We've encountered a situation where Gift Cards are being allowed as a payment method for subscriptions. Further, when the subscription renews it charges only the difference between the original order total and what was used on the gift card. Yikes!

The issue stems from the [cartHasSubscriptionProducts](https://github.com/hps/heartland-woocommerce-plugin/blob/de6df84fcdb4c7be403afb5c5935e4986dedb7e3/classes/class-wc-gateway-securesubmit-giftcards.php#L331) function which doesn't have all of the logic needed to determine if a cart includes subscription products. Instead, use the `cart_contains_subscription` function from the `WC_Subscriptions_Cart` object which should be much more reliable than rolling your own logic to determine if the cart has subscription products.

Proposed fix:

```php
    protected function cartHasSubscriptionProducts()
    {
        if (!method_exists('WC_Subscriptions_Cart', 'cart_contains_subscription')) {
            return false;
        }

        return WC_Subscriptions_Cart::cart_contains_subscription();
    }
```

**Comment by securesubmit-buildmaster** [comment]
Hi @tflight,

Thanks for bringing this to our attention! This will be corrected for in our next release.
