### ISSUE TITLE
Unable to Activate

### ISSUE THREAD

**Issue by jmbullis** [hps/heartland-woocommerce-plugin#36]
Parse error: syntax error, unexpected '.', expecting ',' or ';' in /home/checkyoursite/public_html/dev/veracityrx.com/wp-content/plugins/heartland-woocommerce-plugin-master/gateway-securesubmit.php on line 14

**Comment by slogsdon** [comment]
@jmbullis Sorry about that! We've pushed an update to master that corrects this. Please let us know if you run into any other issues.
