### ISSUE TITLE
Style issue w/ card saving

### ISSUE THREAD

**Issue by chrisvanpatten** [hps/heartland-woocommerce-plugin#41]
I've noticed an issue with the style around the new credit card field, depending on your card saving settings.

If you're logged out, and have card saving disabled, you get the expected look:

![checkout_ _vpm_hps_test](https://cloud.githubusercontent.com/assets/1231306/13497675/a9d91552-e124-11e5-8555-1a08e62088c1.png)

However, if you log in, and still have card saving disabled, you get this:

![checkout_ _vpm_hps_test](https://cloud.githubusercontent.com/assets/1231306/13497815/2d691854-e125-11e5-9a01-08f617b1157a.png)

It appears that the style of that field is coupled to whether or not you're logged in, when it should probably  be coupled to the status of the card saving option.

**Comment by slogsdon** [comment]
Nice catch, @chrisvanpatten! I'll take a look here to see what may be going on.
