### ISSUE TITLE
Error creating PayPal Portico Session

### ISSUE THREAD

**Issue by asatnik11** [hps/heartland-woocommerce-plugin#75]
We're receiving the following error when we try to check out using the SecureSubmit PayPal method:

> Error creating PayPal Portico Session:  "Transaction rejected because the provided data was invalid.  NameValuePair Name: Name Value contains non ascii or empty data. Occurrence 1."

I worked with Heartland support and they tracked the problem down to our product names containing a ® symbol.  Once I removed the ® from the product variation name I was able to successfully complete an order using PayPal.  Hopefully you can add data sanitization to prevent this moving forward.

**Comment by ChessMess** [comment]
Thanks for verifying, we will review adding this to the plugin.
